### ISSUE TITLE
Missing Requirements and Installation Insturctions

### ISSUE THREAD

**Issue by jan-niklasjaensch** [ptc-iot-sharing/ThingworxPortableScripts#1]
Your README.md is missing some software requirements and some instructions for installing.

When trying to run the `startThingworx.bat` the error message.
“The system cannot find the path specified.” is displayed. This is due to the missing of the `bin` directory containing the `catalina.bat`.
![grafik](https://github.com/ptc-iot-sharing/ThingworxPortableScripts/assets/158297229/b6fd3c8f-67b4-467d-a1b9-19e405f443e5)

Are there some more requirements I'm missing?

Furthermore, a hint that a Thingworx.war file should be added to the webapps directory would have been nice.

**Comment by stefan-lacatus** [comment]
Thank you for raising up this issue. 

I'll update the readme file to contain some initial setup instructions with tomcat setup + adding the `Thingworx.war` file.

**Comment by stefan-lacatus** [comment]
I've updated the `README.MD` file with additional instructions for the initial setup of the package. Hope it helps.
